### PR TITLE
Serve /.well-known/acme-challenge/ for http-01 challenge.

### PR DESCRIPTION
**Pull request by ShaneMcC**
Issue csmith/docker-automatic-nginx-letsencrypt#3

### CODE REVIEW

**Comment by ShaneMcC** [comment]
Related: csmith/docker-service-nginx#5

**Comment by csmith** [comment]
Feels like the file shouldn't be called redirect-http.conf now it's doing other stuff!

**Comment by ShaneMcC** [comment]
Want me to rename it redirect-http-and-letsencrypt.conf? :D

Seems like it still belongs in redirect-http.conf as if we're serving the well-known out of the https server blocks it should also be part of any redirect-http.conf to make things just-work

**Comment by csmith** [comment]
How about default-server.conf?

**Pull request merged**
